### ISSUE TITLE
Unexpected behavior when removing a XxxMeta class from a profile

### ISSUE THREAD

**Issue by jechterhoff** [ShapeChange/ProfileManagementTool#10]
When removing an XxxMeta class from a profile, unexpected behaviour occurs.

The following test model was exported with ShapeChange, and imported by the PMT:
 
![featuretypecode classes](https://user-images.githubusercontent.com/4831647/35445641-8bb9e392-02b2-11e8-9c81-df10da22ef6e.jpg)

Steps to reproduce:

- Add all classes to the profile.
- Ensure that none of the special model views is enabled.
- In the model tree, select FeatureTypeCodeMeta. Then in the details pane, select the profile pane and click the slider once to remove the class from the profile.
   - FeatureTypeCodeMeta still belongs to the profile. The slider has not changed its state (it is still shown as active). In the model tree, the class is also shown as belonging to the profile.
   - When switching from the profiles pane to the properties pane, attribute 'valueOrReason' is shown as belonging to the profile.
   - In the model tree, class FeatureTypeCode is shown as not belonging to the profile.
   - Two error messages are shown:
      - _Consistency error in class FeatureTypeCodeReason: Property value is included in profile, but its type FeatureTypeCode is not_
      - _Consistency error in class FeatureTypeCodeMeta: Property valueOrReason is included in profile, but its type FeatureTypeCodeReason is not_
- Switch back to the profile pane (of class FeatureTypeCodeMeta) and click the slider again. 
   - FeatureTypeCodeMeta and FeatureTypeCodeReason are now shown as no longer belonging to the profile.
   - Switching to the properties pane, attribute 'valueOrReason' is still shown as belonging to the profile.
   - Four error messages are indicated, but the error list only contains two messages:
      - _Consistency error in class FeatureTypeCodeReason: Property value is included in profile, but its class FeatureTypeCodeReason is not_
         - This message does not fit. The type of 'value' is FeatureTypeCode, not FeatureTypeCodeReason.
      - _Consistency error in class FeatureTypeCodeMeta: Property valueOrReason is included in profile, but its class FeatureTypeCodeMeta is not_
         - This message also does not fit, since the type of ‘valueOrReason’ is FeatureTypeCodeReason.

When selecting a different model element in the model tree, after clicking the slider in the second - or third - step (to remove FeatureTypeCodeMeta from the profile), then FeatureTypeCodeMeta, FeatureTypeCodeReason, and FeatureTypeCode as well as their properties are shown as not belonging to the profile (which would be correct). However, the PMT still indicates that there are errors (two or four).

**Comment by azahnen** [comment]
This was a side effect of the change in 36bfcce182e42f28fecf3f8fb6e5c027ef1b32bf (fix for consistency check on type removal). 
I reverted that change and provided a fix for the original issue that does not change the behavior.
