### ISSUE TITLE
xml validation

### ISSUE THREAD

**Issue by azahnen** [ShapeChange/ProfileManagementTool#9]
I am afraid XSD 1.1 validation will not be possible. In a basic test, it seemed to be enough to replace "all" with "sequence" to get XSD 1.0 compliance. That should be discussed.

**Comment by jechterhoff** [comment]
"all" was introduced to support extensibility. I was under the assumption that the PMT does not need to validate a given model (nice-to-have). It just parses the information it needs from the XML, according to the elements it understands (SAX based). We can certainly discuss this in more detail.

**Comment by azahnen** [comment]
I thought this was a required feature, but it is not in the documentation, so I was wrong.
Not validating and just parsing known elements would also be my preferred solution, so I will close this for now.
